### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by patzielinski** [JacksonQu/Software-Supply-Chain-Security-Assignment1#1]
Docstrings might help clarify some functions, even though they're rather simple.

https://github.com/JacksonQu/Software-Supply-Chain-Security-Assignment1/blob/d446488fdbda84f8264478efa141aa9ba9dba792/main.py#L9

**Comment by JacksonQu** [comment]
Fixed in branch [origin/fix-issue-1](https://github.com/JacksonQu/Software-Supply-Chain-Security-Assignment1/tree/fix-issue-1)
