### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by patzielinski** [JacksonQu/Software-Supply-Chain-Security-Assignment1#2]
The formatting in this function makes it a bit difficult to read; some strategic line breaks and comments might help.

https://github.com/JacksonQu/Software-Supply-Chain-Security-Assignment1/blob/d446488fdbda84f8264478efa141aa9ba9dba792/main.py#L37

**Comment by JacksonQu** [comment]
Fixed in branch [origin/fix-issue-2](https://github.com/JacksonQu/Software-Supply-Chain-Security-Assignment1/tree/fix-issue-2)
